import Foundation

// Interface language is app-wide and independent of imported book/dictionary content.
enum AppLanguage {
    static func locale(_ choice: String, preferred: [String] = Locale.preferredLanguages) -> Locale {
        if choice != "system" { return Locale(identifier: choice) }
        return Locale(identifier: preferred.first ?? "en")
    }
    static func text(_ key: String, language: String) -> String {
        let language = language.replacingOccurrences(of: "_", with: "-")
        return language.hasPrefix("zh") && !language.hasPrefix("zh-Hant") && !language.hasPrefix("zh-TW") && !language.hasPrefix("zh-HK") ? (simplifiedChinese[key] ?? key) : key
    }
    static let simplifiedChinese: [String: String] = [
        "%d books · A little Japanese, every day.": "%d 本书 · 每天读一点日语。",
        "%d saved · %d sent to Anki": "已保存 %d 个 · 已发送 %d 个到 Anki",
        "Daily reading goal: %d minutes": "每日阅读目标：%d 分钟",
        "Dictionary scan length: %d": "词典扫描长度：%d",
        "Fields: ": "字段：",
        "Shelf": "书架",
        "Delay": "延迟",
        "Choose a remote book": "选择远程书籍",

        "%d matches · Scroll for all definitions": "共 %d 条匹配 · 向下滚动查看全部释义",
        "30 days": "30 天",
        "7 days": "7 天",
        "90 days": "90 天",
        "A word opens a world.": "一词一世界。",
        "ANKI NOTES": "Anki 卡片",
        "About": "关于",
        "Add Bookmark": "添加书签",
        "Add a note…": "添加笔记…",
        "Add bookmark · ⌘D": "添加书签 · ⌘D",
        "Add field": "添加字段",
        "Add to Anki": "添加到 Anki",
        "Added to Anki": "已添加到 Anki",
        "All books": "全部书籍",
        "Allow duplicate notes": "允许重复笔记",
        "Anki field name": "Anki 字段名",
        "Appearance": "外观",
        "Audio": "音频",
        "Audio URL template": "音频 URL 模板",
        "Audiobook": "有声书",
        "Audiobooks": "有声书",
        "Back to library": "返回书库",
        "Back up this Mac, or exchange books and reading progress with ッツ Reader.": "备份此 Mac 的数据，或与 ッツ Reader 交换书籍和阅读进度。",
        "Background hex": "背景色十六进制值",
        "Bilingual": "双语",
        "Books, dictionaries, saved words, bookmarks and settings.": "书籍、词典、生词、书签和设置。",
        "CHARACTERS": "已读字数",
        "Cancel": "取消",
        "Cancel sign-in": "取消登录",
        "Characters read": "已读字数",
        "Choose": "选择",
        "Choose a book": "选择书籍",
        "Click a word in your book, or search above.": "点击书中的单词，或在上方搜索。",
        "Click a word · Shift + hover to look up": "点击单词，或按住 Shift 悬停查词",
        "Connect / refresh fields": "连接或刷新字段",
        "Connect Google Drive": "连接 Google Drive",
        "Contents": "目录",
        "Contents, search and bookmarks": "目录、搜索与书签",
        "Create": "创建",
        "Create backup…": "创建备份…",
        "Custom": "自定义",
        "Custom CSS": "自定义 CSS",
        "Deck": "牌组",
        "Definitions": "释义",
        "Desktop client ID": "桌面客户端 ID",
        "Desktop client secret (if supplied by Google)": "桌面客户端密钥（若 Google 提供）",
        "Dictionaries": "词典",
        "Dictionary": "词典",
        "Dictionary order controls definition priority.": "词典顺序决定释义的优先级。",
        "Direct audio": "直接音频",
        "Disconnect": "断开连接",
        "Download a ZIP, then choose Import dictionary ZIP… without unzipping it.": "下载 ZIP 后点击“导入词典 ZIP…”，无需解压。",
        "Endpoint": "接口地址",
        "Every page adds up.": "每一页都是积累。",
        "Exchange the bookdata ZIP used by ッツ. Progress can also be exported or imported as a separate JSON file.": "交换 ッツ 使用的 bookdata ZIP，也可单独导入或导出进度 JSON。",
        "Exclude from Anki": "不用于 Anki",
        "Export TSV…": "导出 TSV…",
        "Export bookdata…": "导出书籍数据…",
        "Export progress…": "导出进度…",
        "Field templates": "字段模板",
        "Follow system": "跟随系统",
        "Font": "字体",
        "GOOGLE DRIVE": "Google Drive",
        "Google Drive · ッツ sync": "Google Drive · ッツ 同步",
        "Highlight selection": "高亮选中词语",
        "Import Books…": "导入书籍…",
        "Import Dictionary…": "导入词典…",
        "Import EPUB": "导入 EPUB",
        "Import EPUB…": "导入 EPUB…",
        "Import Yomitan ZIP…": "导入 Yomitan ZIP…",
        "Import a Japanese EPUB, add your Yomitan dictionaries, and start reading.\nYour library lives on this Mac.": "导入日语 EPUB，添加 Yomitan 词典，即可开始阅读。\n书库保存在此 Mac 上。",
        "Import a Yomitan dictionary ZIP to look up words offline, including conjugated forms.": "导入 Yomitan 词典 ZIP 即可离线查词，也支持变形词。",
        "Import audio…": "导入音频…",
        "Import bookdata…": "导入书籍数据…",
        "Import dictionary ZIP…": "导入词典 ZIP…",
        "Import dictionary…": "导入词典…",
        "Import font…": "导入字体…",
        "Import progress…": "导入进度…",
        "Inspired by Hoshi Reader. Offline dictionary lookup uses its hoshidicts engine, including Yomitan's Japanese deinflection rules. This is an independent GPL-3.0 application.": "灵感来自 Hoshi Reader。离线查词使用其 hoshidicts 引擎及 Yomitan 日语变形还原规则。这是一款独立的 GPL-3.0 应用。",
        "Installed dictionaries": "已安装的词典",
        "Interface language": "界面语言",
        "Japanese names: people and places": "日语人名与地名",
        "Japanese voice": "日语语音",
        "Japanese–English definitions and examples · Start here": "日英释义和例句 · 推荐入门",
        "Japanese–Simplified Chinese · Community machine translation; download the dictionary ZIP from Releases": "日语—简体中文 · 社区机器翻译版；请在发布页下载词典 ZIP",
        "Jitendex website": "Jitendex 网站",
        "Kanji meanings and readings · English": "汉字释义和读音 · 英文",
        "Keep your place.": "保存你的阅读进度。",
        "Lapis preset": "Lapis 预设",
        "Library": "书库",
        "Listen": "听发音",
        "Loading…": "加载中…",
        "Local backup": "本地备份",
        "Local book": "本地书籍",
        "Look up": "查词",
        "Look up Japanese": "查找日语词汇",
        "Make room for a good book": "为好书留个位置",
        "Match SRT subtitles…": "匹配 SRT 字幕…",
        "Mining definition": "制卡释义",
        "Monolingual": "单语",
        "More dictionaries": "更多词典",
        "Name": "名称",
        "Navigation": "导航",
        "New Bookshelf": "新建书架",
        "New shelf": "新建书架",
        "Next Chapter": "下一章",
        "Night": "夜间",
        "No bundled commercial books or dictionaries. Import the dictionaries you use with Yomitan. Online pronunciation and Google Drive sync only run when requested.": "不附带商业书籍或词典。请导入你在 Yomitan 中使用的词典。在线发音和 Google Drive 同步仅在主动操作时运行。",
        "No dictionaries imported yet": "尚未导入词典",
        "No matching entries": "没有匹配的词条",
        "None": "无",
        "Note type": "笔记类型",
        "OK": "确定",
        "Open a book → Contents → Audiobook. Import an MP3 or M4B and matching SRT subtitles to follow along. Use {sasayaki-audio} to mine the active cue into Anki.": "打开书籍 → 目录 → 有声书。导入 MP3 或 M4B 和匹配的 SRT 字幕即可跟读。使用 {sasayaki-audio} 将当前片段音频加入 Anki。",
        "Optional API key": "API 密钥（可选）",
        "Paper": "纸张",
        "Pause / Resume Statistics": "暂停或继续统计",
        "Pause / resume reading statistics": "暂停或继续阅读统计",
        "Period": "时间范围",
        "Pitch accent": "音调",
        "Play source audio; use Japanese speech if unavailable": "播放音源；不可用时使用日语系统语音",
        "Previous Chapter": "上一章",
        "Pull selected book from ッツ": "从 ッツ 下载所选书籍",
        "Push replaces remote progress with the selected local position. Pull replaces local progress for a matching title. Statistics keep the newer record for each day. In ッツ, disable password encryption and sync from Browser DB to GDrive before pulling here.": "上传会以所选本地进度替换远程进度；下载会替换同名书籍的本地进度。统计保留每天较新的记录。下载前，请在 ッツ 中关闭密码加密，并从 Browser DB 同步到 GDrive。",
        "Push selected book to ッツ": "将所选书籍上传到 ッツ",
        "READING TIME": "阅读时间",
        "Read": "阅读",
        "Read aloud using the Mac's Japanese voice": "使用 Mac 的日语语音朗读",
        "Reading": "阅读",
        "Reading appearance": "阅读外观",
        "Reading minutes": "阅读分钟数",
        "Reading time pauses when this app is in the background or idle for 90 seconds. Large jumps and backward scrolling don't count as newly read characters.": "应用进入后台或闲置 90 秒后暂停计时。大幅跳转和向后滚动不计入新增阅读字数。",
        "Recently read": "最近阅读",
        "Recommended dictionaries · Download": "推荐词典 · 下载",
        "Reconnect Google Drive": "重新连接 Google Drive",
        "Refresh": "刷新",
        "Remote book": "远程书籍",
        "Remove": "删除",
        "Remove book…": "删除书籍…",
        "Remove saved word": "删除已保存的单词",
        "Remove shelf": "删除书架",
        "Replay line": "重播本句",
        "Restore…": "恢复备份…",
        "Reveal imported EPUB": "在访达中显示导入的 EPUB",
        "Run desktop Anki with AnkiConnect installed. Configure the note fields below, then mine directly from the reader.": "启动已安装 AnkiConnect 的桌面版 Anki。配置下方笔记字段后，即可从阅读器直接制卡。",
        "Save word": "保存单词",
        "Saved": "已保存",
        "Search": "搜索",
        "Search title or author": "搜索书名或作者",
        "Settings": "设置",
        "Setup guide": "设置指南",
        "Show local library folder": "打开本地书库文件夹",
        "Show ruby readings": "显示注音",
        "SimpleReader for macOS": "SimpleReader macOS 版",
        "Size": "字号",
        "Sort": "排序",
        "Source type": "音源类型",
        "Spacing": "行距",
        "Speed": "速度",
        "Statistics": "统计",
        "Supported Hoshi markers": "支持的 Hoshi 占位符",
        "Sync & Backup": "同步与备份",
        "Sync audiobook position": "同步有声书进度",
        "Sync reading statistics": "同步阅读统计",
        "THIS MAC": "此 Mac",
        "TODAY": "今天",
        "Tags separated by spaces": "标签（用空格分隔）",
        "Template": "模板",
        "Text hex": "文字颜色十六进制值",
        "The waveform button uses the Mac's Japanese speech voice. The speaker button uses this source.": "波形按钮使用 Mac 的日语系统语音，扬声器按钮使用此音源。",
        "Theme": "主题",
        "Title": "书名",
        "Try another term, or add another dictionary.": "试试其他词语，或添加另一本词典。",
        "Try sample book & dictionary": "试用示例书籍和词典",
        "Use a Google OAuth Desktop client from the same Cloud project as your ッツ client. Enable the Drive API and drive.file scope. Credentials are stored in macOS Keychain.": "使用与 ッツ 客户端同一 Cloud 项目的 Google OAuth 桌面客户端。启用 Drive API 和 drive.file 权限。凭据保存在 macOS 钥匙串中。",
        "Use a direct audio URL or a Yomitan JSON audio source, including a local AnkiConnect Android audio server. {term} and {reading} are replaced with the looked-up word.": "使用直接音频 URL 或 Yomitan JSON 音源，也支持本地 AnkiConnect Android 音频服务器。{term} 和 {reading} 会替换为所查词语及其读音。",
        "Use for mining": "用于制卡",
        "Vertical Japanese text": "日语竖排",
        "Vocabulary": "生词本",
        "WORDS LOOKED UP": "查词次数",
        "White": "白色",
        "Word pronunciation": "单词发音",
        "Words worth keeping": "值得记住的单词",
        "Yomitan JSON": "Yomitan JSON",
        "Yomitan dictionaries": "Yomitan 词典",
        "Yomitan terms, frequencies, pitch accents and kanji. Search works offline after import.": "支持 Yomitan 词条、词频、音调和汉字。导入后即可离线搜索。",
        "Your dictionaries": "你的词典",
        "Your reading room": "你的阅读室",
        "ッツ files": "ッツ 文件"
    ]
}
func L(_ key: String, _ arguments: CVarArg...) -> String {
    let language = AppLanguage.locale(UserDefaults.standard.string(forKey: "interfaceLanguage") ?? "system").identifier
    let value = AppLanguage.text(key, language: language)
    return arguments.isEmpty ? value : String(format: value, locale: AppLanguage.locale(language), arguments: arguments)
}
